import { InsuranceTypes } from "../enums/insuranceType";
import { RegistrationType } from "../enums/registrationType";
import { User } from "./user";

export class Policy{
  Id:number;
  PolicyExpiration:Date;
  Created:Date;
  PolicyBegin:Date;
  PolicyNumberId:number;
  PolicyNumber:string;
  InsuranceTypeId:number;
  Price:number;
  UserId:number;
  InsuranceId:number;
  InsuranceName:string;
  PolicyHolderId:number;
  PolicyHolder:string;
  UserFullName:string;
  Users:User[];
  GreenCardId:number;
  Percent:number;
  TotalPremium:number;
  MainTotal:number;
  AdminTechnicalInspectionId:number;
  SupplierId:number;
  Other:number;
  SecondPercent:number;
  SecondMainTotal:number;
  DirectReverse:boolean;
  RegistrationType:RegistrationType;
  TechnicalInspectionId:number;
  CarAccidentCompensation:number;
  MainOfficeId: number;
  InsuranceTypeLabel:string;
  PolicyHolderLogId:number;
  PolicyNumberStatus: number;
  RemainingDebt : number;
  NumberOfInstallment : number;
  Payment : number;
  ExpectedPaymentDate : Date;
  PartnerId:number;
  VoucherId:number;
  PaymentMethod:string;
  PolicyNumberFormData:string;
  TotalPaymentPrice : number;
  CompanyName : string;
}
